"""
Proctored test engine — MCQ generation and scoring.

Three modules:
- General Aptitude: 10 MCQs, 15 min (all roles)
- AI Proficiency: 5 MCQs, 10 min (if ai_required=True)
- English Language: 10 questions, 10 min (all roles)

Scoring weights: Aptitude 40% + AI 30% + English 30%.
Pass threshold: 60/100 overall, min 50 per module.

All questions generated by Claude Haiku and stored in hr_test_sessions.questions JSONB.
"""

from __future__ import annotations

import json
import logging
import secrets
from typing import Any

from tenacity import retry, stop_after_attempt, wait_exponential

logger = logging.getLogger(__name__)

CLAUDE_HAIKU_MODEL = "claude-haiku-4-5-20251001"
PASS_THRESHOLD = 60.0
MODULE_PASS_THRESHOLD = 50.0

APTITUDE_WEIGHT = 0.40
AI_WEIGHT = 0.30
ENGLISH_WEIGHT = 0.30  # Redistributed to 0.45/0.55 if no AI module


_APTITUDE_PROMPT = """Generate exactly 10 general aptitude MCQs for a professional hiring test.
Cover: logical reasoning (3), numerical ability (3), data interpretation (2), verbal reasoning (2).
Each question should be appropriate for mid-senior professionals.

Respond ONLY with a JSON array:
[
  {{
    "question": "<question text>",
    "options": ["<A>", "<B>", "<C>", "<D>"],
    "correct_index": <0-3>,
    "module": "aptitude"
  }},
  ...
]
Generate all 10 questions."""

_AI_PROMPT = """Generate exactly 5 MCQs testing practical AI knowledge for a professional hiring test.
Cover: LLMs and prompting (2), AI tools in business (2), data and ML basics (1).
Avoid highly technical ML math — focus on applied understanding.

Respond ONLY with a JSON array of 5 questions:
[
  {{
    "question": "<question text>",
    "options": ["<A>", "<B>", "<C>", "<D>"],
    "correct_index": <0-3>,
    "module": "ai"
  }},
  ...
]"""

_ENGLISH_PROMPT = """Generate exactly 10 English language questions for a professional hiring test.
Cover: grammar correction (3), email writing comprehension (3), reading comprehension (2), vocabulary in context (2).

Respond ONLY with a JSON array of 10 questions:
[
  {{
    "question": "<question text>",
    "options": ["<A>", "<B>", "<C>", "<D>"],
    "correct_index": <0-3>,
    "module": "english"
  }},
  ...
]"""


def generate_test_token() -> str:
    """Generate a cryptographically random URL-safe token."""
    return secrets.token_urlsafe(32)


def score_test(
    *,
    questions: dict[str, list[dict]],
    answers: dict[str, list[int]],
    ai_required: bool,
) -> dict[str, Any]:
    """
    Score a submitted test.

    Returns:
    - aptitude_score: 0-100
    - ai_score: 0-100 (None if not required)
    - english_score: 0-100
    - overall_score: 0-100 (weighted)
    - passed: bool
    - module_results: dict per module
    """
    def _score_module(module: str) -> float:
        qs = questions.get(module, [])
        ans = answers.get(module, [])
        if not qs:
            return 0.0
        correct = sum(1 for i, q in enumerate(qs) if i < len(ans) and ans[i] == q["correct_index"])
        return round(correct / len(qs) * 100, 1)

    aptitude = _score_module("aptitude")
    english = _score_module("english")
    domain_score = _score_module("domain") if "domain" in questions else None
    ai_score = _score_module("ai") if ai_required else None

    # Weights: aptitude 35%, english 30%, domain 35% (if present); else aptitude 55%, english 45%
    if domain_score is not None and ai_required and ai_score is not None:
        overall = round(aptitude * 0.30 + english * 0.25 + domain_score * 0.25 + ai_score * 0.20, 1)
    elif domain_score is not None:
        overall = round(aptitude * 0.35 + english * 0.30 + domain_score * 0.35, 1)
    elif ai_required and ai_score is not None:
        overall = round(aptitude * APTITUDE_WEIGHT + ai_score * AI_WEIGHT + english * ENGLISH_WEIGHT, 1)
    else:
        overall = round(aptitude * 0.55 + english * 0.45, 1)

    modules_pass = all([
        aptitude >= MODULE_PASS_THRESHOLD,
        english >= MODULE_PASS_THRESHOLD,
        (domain_score >= MODULE_PASS_THRESHOLD if domain_score is not None else True),
        (ai_score >= MODULE_PASS_THRESHOLD if ai_required and ai_score is not None else True),
    ])
    passed = overall >= PASS_THRESHOLD and modules_pass

    return {
        "aptitude_score": aptitude,
        "ai_score": ai_score,
        "english_score": english,
        "domain_score": domain_score,
        "overall_score": overall,
        "passed": passed,
        "module_results": {
            "aptitude": {"score": aptitude, "passed": aptitude >= MODULE_PASS_THRESHOLD},
            "english": {"score": english, "passed": english >= MODULE_PASS_THRESHOLD},
            **({"domain": {"score": domain_score, "passed": domain_score >= MODULE_PASS_THRESHOLD}} if domain_score is not None else {}),
            **({"ai": {"score": ai_score, "passed": ai_score >= MODULE_PASS_THRESHOLD}} if ai_required and ai_score is not None else {}),
        },
    }


class TestEngine:
    def __init__(self, *, client: Any) -> None:
        self._client = client

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=2, max=10), reraise=True)
    async def _generate_module(self, *, prompt: str, module: str) -> list[dict]:
        message = await self._client.messages.create(
            model=CLAUDE_HAIKU_MODEL,
            max_tokens=2048,
            messages=[{"role": "user", "content": prompt}],
        )
        raw = message.content[0].text.strip()
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            logger.error("Test generation JSON parse error for %s: %.200s", module, raw)
            return []

    async def generate_questions(self, *, role: str, ai_required: bool) -> dict[str, list[dict]]:
        """Generate all test questions. Returns dict keyed by module name."""
        aptitude = await self._generate_module(prompt=_APTITUDE_PROMPT, module="aptitude")
        english = await self._generate_module(prompt=_ENGLISH_PROMPT, module="english")

        result: dict[str, list[dict]] = {"aptitude": aptitude, "english": english}

        if ai_required:
            ai_qs = await self._generate_module(prompt=_AI_PROMPT, module="ai")
            result["ai"] = ai_qs

        return result


_FALLBACK_APTITUDE: list[dict] = [
    {"question": "If a train travels 300 km in 5 hours, what is its average speed?", "options": ["50 km/h", "60 km/h", "70 km/h", "80 km/h"], "correct_index": 1, "module": "aptitude"},
    {"question": "A is 3 years older than B. In 5 years, A will be twice as old as B. How old is B now?", "options": ["1", "2", "3", "4"], "correct_index": 0, "module": "aptitude"},
    {"question": "Which number comes next: 2, 6, 12, 20, 30, ?", "options": ["40", "42", "44", "46"], "correct_index": 1, "module": "aptitude"},
    {"question": "If SALE is coded as VDOH, how is MARK coded?", "options": ["PDUN", "PCUN", "PEUN", "PDVN"], "correct_index": 0, "module": "aptitude"},
    {"question": "A shop sells goods at 20% profit. If cost is $500, selling price is?", "options": ["$550", "$580", "$600", "$620"], "correct_index": 2, "module": "aptitude"},
    {"question": "In a pie chart, one sector covers 90°. What percentage does it represent?", "options": ["20%", "25%", "30%", "35%"], "correct_index": 1, "module": "aptitude"},
    {"question": "All managers are leaders. Some leaders are creative. Which is definitely true?", "options": ["All managers are creative", "Some managers may be creative", "No managers are creative", "All creative people are managers"], "correct_index": 1, "module": "aptitude"},
    {"question": "A can do a job in 10 days, B in 15 days. Together they finish in?", "options": ["5 days", "6 days", "7 days", "8 days"], "correct_index": 1, "module": "aptitude"},
    {"question": "Find the odd one: 121, 144, 169, 196, 225, 250", "options": ["196", "225", "250", "169"], "correct_index": 2, "module": "aptitude"},
    {"question": "If 6 workers complete a task in 8 days, how many days for 4 workers?", "options": ["10", "12", "14", "16"], "correct_index": 1, "module": "aptitude"},
]

_FALLBACK_ENGLISH: list[dict] = [
    {"question": "Choose the correct sentence:", "options": ["He don't know the answer.", "He doesn't knows the answer.", "He doesn't know the answer.", "He not know the answer."], "correct_index": 2, "module": "english"},
    {"question": "Which word means the opposite of 'verbose'?", "options": ["Wordy", "Concise", "Elaborate", "Lengthy"], "correct_index": 1, "module": "english"},
    {"question": "A professional email should begin with:", "options": ["Hey there,", "Dear Mr./Ms. [Name],", "Yo,", "What's up,"], "correct_index": 1, "module": "english"},
    {"question": "Select the correctly punctuated sentence:", "options": ["Its a great day.", "It's a great day.", "Its' a great day.", "It's' a great day."], "correct_index": 1, "module": "english"},
    {"question": "In business writing, 'per your request' means:", "options": ["Against your request", "As you requested", "Before your request", "Despite your request"], "correct_index": 1, "module": "english"},
    {"question": "Which sentence uses the passive voice?", "options": ["The manager approved the report.", "The report was approved by the manager.", "Managers approve reports.", "He will approve the report."], "correct_index": 1, "module": "english"},
    {"question": "'The contract was signed by both parties.' The subject is:", "options": ["Both parties", "The contract", "Signed", "Was"], "correct_index": 1, "module": "english"},
    {"question": "Choose the correct form: 'Neither the manager nor the employees ___ happy.'", "options": ["was", "is", "were", "be"], "correct_index": 2, "module": "english"},
    {"question": "What does 'revert' mean in Indian business English?", "options": ["To go back", "To reply", "To reverse", "To return"], "correct_index": 1, "module": "english"},
    {"question": "Which is the most formal closing for a business email?", "options": ["Cheers,", "Bye,", "Yours sincerely,", "Later,"], "correct_index": 2, "module": "english"},
]

_FALLBACK_DOMAIN: dict[str, list[dict]] = {
    "bd_manager": [
        {"question": "What is the primary goal of a discovery call in B2B sales?", "options": ["Close the deal immediately", "Understand the prospect's pain points and needs", "Pitch the product features", "Schedule a demo"], "correct_index": 1, "module": "domain"},
        {"question": "Which metric measures the percentage of leads that become customers?", "options": ["Churn rate", "Conversion rate", "CAC", "NPS"], "correct_index": 1, "module": "domain"},
        {"question": "SPIN Selling stands for:", "options": ["Strategy, Planning, Insight, Negotiation", "Situation, Problem, Implication, Need-Payoff", "Sales, Prospecting, Influence, Numbers", "Speed, Persistence, Innovation, Networking"], "correct_index": 1, "module": "domain"},
        {"question": "A managed office differs from a co-working space primarily in:", "options": ["Price", "Location", "Customisation and exclusivity for one tenant", "Number of desks"], "correct_index": 2, "module": "domain"},
        {"question": "What is the typical decision-making unit (DMU) for a managed office deal?", "options": ["Only the CEO", "Admin manager only", "CXO + Finance + Admin + HR", "Only Finance"], "correct_index": 2, "module": "domain"},
    ],
    "operations_manager": [
        {"question": "SLA stands for:", "options": ["Service Level Agreement", "Standard Labour Act", "Site Location Audit", "System Load Analysis"], "correct_index": 0, "module": "domain"},
        {"question": "CSAT in facility management measures:", "options": ["Cost savings", "Client satisfaction", "Compliance status", "Carbon footprint"], "correct_index": 1, "module": "domain"},
        {"question": "MEP in facility management refers to:", "options": ["Management, Equipment, Personnel", "Mechanical, Electrical, Plumbing", "Maintenance, Energy, Planning", "Monitoring, Evaluation, Performance"], "correct_index": 1, "module": "domain"},
        {"question": "Which is a key KPI for a facilities operations manager?", "options": ["Sales pipeline value", "Mean Time to Repair (MTTR)", "Website traffic", "Recruiting cost per hire"], "correct_index": 1, "module": "domain"},
        {"question": "PPM in facilities management stands for:", "options": ["Planned Preventive Maintenance", "Property and Plant Management", "Project Performance Metric", "People Process Management"], "correct_index": 0, "module": "domain"},
    ],
}
_FALLBACK_DOMAIN_DEFAULT: list[dict] = [
    {"question": "What does KPI stand for?", "options": ["Key Performance Indicator", "Key Process Input", "Key Planning Insight", "Key Profit Index"], "correct_index": 0, "module": "domain"},
    {"question": "Which is the best approach to managing a tight deadline?", "options": ["Work alone to avoid distraction", "Prioritise tasks by impact and communicate progress", "Ask for an extension immediately", "Ignore lower priority tasks permanently"], "correct_index": 1, "module": "domain"},
    {"question": "What does CRM stand for?", "options": ["Customer Relationship Management", "Client Revenue Metric", "Company Risk Management", "Customer Retention Model"], "correct_index": 0, "module": "domain"},
    {"question": "A SWOT analysis evaluates:", "options": ["Sales, Work, Operations, Talent", "Strengths, Weaknesses, Opportunities, Threats", "Strategy, Workflow, Output, Timing", "Systems, Workforce, Objectives, Trends"], "correct_index": 1, "module": "domain"},
    {"question": "When is it appropriate to escalate an issue to your manager?", "options": ["Never — handle everything yourself", "Only when you have failed", "When it's beyond your authority or affects the team", "Always, for every decision"], "correct_index": 2, "module": "domain"},
]


class TestEngine:
    def __init__(self, *, client: Any) -> None:
        self._client = client

    @retry(stop=stop_after_attempt(2), wait=wait_exponential(multiplier=1, min=2, max=8), reraise=False)
    async def _generate_module(self, *, prompt: str, module: str) -> list[dict] | None:
        try:
            message = await self._client.messages.create(
                model=CLAUDE_HAIKU_MODEL,
                max_tokens=2048,
                messages=[{"role": "user", "content": prompt}],
            )
            raw = message.content[0].text.strip()
            return json.loads(raw)
        except Exception as exc:
            logger.warning("Question generation failed for %s (%s), will use fallback.", module, exc)
            return None

    async def generate_questions(self, *, role: str, ai_required: bool) -> dict[str, list[dict]]:
        """Generate all test questions. Falls back to hardcoded bank if Claude unavailable."""
        aptitude_raw = await self._generate_module(prompt=_APTITUDE_PROMPT, module="aptitude")
        aptitude = aptitude_raw if aptitude_raw else _FALLBACK_APTITUDE

        english_raw = await self._generate_module(prompt=_ENGLISH_PROMPT, module="english")
        english = english_raw if english_raw else _FALLBACK_ENGLISH

        domain = _FALLBACK_DOMAIN.get(role, _FALLBACK_DOMAIN_DEFAULT)

        result: dict[str, list[dict]] = {"aptitude": aptitude, "english": english, "domain": domain}

        if ai_required:
            ai_raw = await self._generate_module(prompt=_AI_PROMPT, module="ai")
            if ai_raw:
                result["ai"] = ai_raw

        return result


def make_test_engine() -> TestEngine:
    import anthropic
    from src.config import get_settings
    client = anthropic.AsyncAnthropic(api_key=get_settings().anthropic_api_key)
    return TestEngine(client=client)
